/run/numberOfThreads 2
# Initialize kernel
/run/initialize
#
#/Micromegas/det/SetGeomID 12
#
##P=1MeV
##/Micromegas/det/setField 223 gauss
##P=100keV
##/Micromegas/det/setField 22.5 gauss
##P=5MeV
##/Micromegas/det/setField 500 gauss
##E=100keV
##/Micromegas/det/setField 81.5 gauss
##P=3.5MeV -> 778 G
#/Micromegas/det/setField 575 gauss
#
#/Micromegas/det/setCupThick 100 um
#
#/Leetech/det/SetCollimatorEntranceGapX 20 mm
#/Leetech/det/SetCollimatorEntranceGapY 20 mm
#/Leetech/det/SetCollimatorExit1GapX 20 mm
#/Leetech/det/SetCollimatorExit1GapY 20 mm
#
##equal to first colim gap
##/Micromegas/det/setApertureRaduis 1 cm
#/Micromegas/det/setApertureRaduis 2 cm
#
##equal to sec colim gap
##/Micromegas/det/setApertureThick 1.4 cm
#/Micromegas/det/setApertureThick 2 cm
#
##/Micromegas/det/setDet1InRad 0 mm unusable for now
#
#/Micromegas/det/setDet1OutRad 1 cm
#
##distance from the edge to beginning of the collimator system
#/Micromegas/det/setDet1X 20 mm
#
#/Micromegas/det/setRotationDeg 23 deg
##/Micromegas/det/setRotationAddDist 6.5 cm
#/Micromegas/det/setRotationAddDist 65 cm
#
#/Micromegas/det/setMaxStep 10 mm
#/Micromegas/det/setMaxLength 5.0 m
#/Micromegas/det/setMaxTime 20 s
#/Micromegas/det/setMinEkin 10 keV
#/Micromegas/det/setMionRang 0.01 mm
#
#/Micromegas/det/update
#
##gamma, e-, e+, mu-, mu+, pi-, pi+, kaon-, kaon+, anti_proton, proton
#/Micromegas/gun/PerticleType e-
#
## settings for aproximate parameters of collimators
##/Micromegas/gun/ParticlePosition -50 0 -60.0
##/Micromegas/gun/ParticleDirection 0.0 0.0 1.0
##/Micromegas/gun/ParticleDirectionRMS 0.1 0.1 0
##/Micromegas/gun/ParticleMomentum 0.5 1.5 -999
##/Micromegas/gun/ParticleMomentum 1 1 -999
#
## settings for don't use window 20mkm
##/Micromegas/gun/ParticlePosition -150.0 0 -200.0
##/Micromegas/gun/ParticleDirection 0.0 0.0 1.0
##/Micromegas/gun/ParticleDirectionRMS 0 0 0
##/Micromegas/gun/ParticleMomentum 3.5 3.5 -999
#
## FIGHT settings
#/Micromegas/gun/ParticleDirection 39 0.0 92
#/Micromegas/gun/ParticleDirectionRMS 0.0 0.0 0.0
#/Micromegas/gun/ParticleMomentum 3.5 3.5 -999
#
## DIRECT TO DETECTOR ssettings
##/Micromegas/gun/ParticlePosition 210 0 -161.193
##/Micromegas/gun/ParticleDirection 39 0.0 92
##/Micromegas/gun/ParticleDirectionRMS 0.0 0.0 0.0
##/Micromegas/gun/ParticleMomentum 5.0 5.0 -999
#
#/Leetech/RootFile Test
#/Micromegas/printModulo 100000

/run/beamOn 100000



