/Micromegas/det/setCupThick 2 mm

/Leetech/det/SetCollimatorEntranceGapX 20.000000 mm
/Leetech/det/SetCollimatorEntranceGapY 20.000000 mm
/Leetech/det/SetCollimatorExit1GapX 1.000000 mm
/Leetech/det/SetCollimatorExit1GapY 1.000000 mm

#equal to first colim gap
#/Micromegas/det/setApertureRaduis 1 cm
/Micromegas/det/setApertureRaduis 2 cm

#equal to sec colim gap
#/Micromegas/det/setApertureThick 1.4 cm
/Micromegas/det/setApertureThick 2 cm

#/Micromegas/det/setDet1InRad 0 mm unusable for now

/Micromegas/det/setDet1OutRad 1 cm

#distance from the edge to beginning of the collimator system
/Micromegas/det/setDet1X 20 mm

/Micromegas/det/setRotationDeg 23 deg
#/Micromegas/det/setRotationAddDist 6.5 cm
/Micromegas/det/setRotationAddDist 65 cm

/Micromegas/det/setMaxStep 10 mm
/Micromegas/det/setMaxLength 5.0 m
/Micromegas/det/setMaxTime 20 s
/Micromegas/det/setMinEkin 10 keV
/Micromegas/det/setMionRang 0.01 mm

/run/numberOfThreads 1
/run/initialize

/Leetech/det/setField 525 gauss

#/gps/position -203.000        0 -397.101      mm        
#/gps/direction  0        0  1 

# direction corresponds to 23 degrees beam pipe angle

# for 0 deg beampipe angle
#/gps/position -203    0    -300 mm
#/gps/direction 0    0    1

# beampipe (23 deg inclined) center
#/gps/position -281.146    0    -397.101 mm
#/gps/direction 0.3907311284892737    0    0.9205048534524404
#
#/gps/energy 3.5 MeV

/Leetech/gun/SourceROOTFile /home/vlad/10g4work/LeetechRuns/EntranceCollScans/EntranceCollScan_7detectors/opening=19mm_E=3500keV/leetech.root
/Leetech/gun/tree AfterEntranceColl

/Leetech/OutRootFile leetech_p1

/run/beamOn 100

