#!/bin/bash

# set momentum of primary electrons
E_primaries=3.5
python ../pyscripts/change_parameter.py /Micromegas/gun/ParticleEnergy "$E_primaries MeV"

# set the target thickness
target=4
python ../pyscripts/change_parameter.py /Micromegas/det/setCupThick "$target mm"

# cycle through magnetic field values
for B_field in {0..20..100}
  do
    python ../pyscripts/change_parameter.py /Micromegas/det/setField "$B_field gauss"
    python ../pyscripts/run.py -n 4 --noreadme -o "../LeetechRuns/B_field_scan_Target=$target mm_$E_primaries MeV_B=$B_field G"
  done
