#!/bin/bash

# set momentum of primary electrons
P_primaries=3.5
./../pyscripts/change_parameter.py /Micromegas/gun/ParticleMomentum "$P_primaries $P_primaries -999"

# set the target thickness
target=4
./../pyscripts/change_parameter.py /Micromegas/det/setCupThick "$target mm"

# cycle through magnetic field values
for B_field in {0..20..500}
  do
    ./../pyscripts/change_parameter.py /Micromegas/det/setField "$B_field gauss"
    ./../pyscripts/run.py -n 4 --remote --noreadme -o "../LeetechRuns/B_field_scan_Target=4mm_$P_primaries MeV_B=$B_field G"
  done
